import type { Movie } from './types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Interestelar',
    year: 2014,
    rating: 4.8,
    genre: ['Ficção Científica', 'Drama'],
    coverUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&h=675&fit=crop',
    type: 'movie',
    description: 'Uma equipe de exploradores viaja através de um buraco de minhoca no espaço na tentativa de garantir a sobrevivência da humanidade.',
    duration: '2h 49min',
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    language: 'Inglês',
    quality: '4K',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Breaking Bad',
    year: 2008,
    rating: 4.9,
    genre: ['Drama', 'Crime'],
    coverUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=1200&h=675&fit=crop',
    type: 'series',
    description: 'Um professor de química do ensino médio diagnosticado com câncer se transforma em produtor de metanfetamina.',
    seasons: 5,
    director: 'Vince Gilligan',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    language: 'Inglês',
    quality: 'HD',
    isFeatured: false,
  },
  {
    id: '3',
    title: 'O Poderoso Chefão',
    year: 1972,
    rating: 4.9,
    genre: ['Crime', 'Drama'],
    coverUrl: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=1200&h=675&fit=crop',
    type: 'movie',
    description: 'O envelhecido patriarca de uma dinastia do crime organizado transfere o controle de seu império para seu filho relutante.',
    duration: '2h 55min',
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    language: 'Inglês',
    quality: 'HD',
    isFeatured: false,
  },
  {
    id: '4',
    title: 'Stranger Things',
    year: 2016,
    rating: 4.7,
    genre: ['Terror', 'Ficção Científica'],
    coverUrl: 'https://imgs.search.brave.com/ZwZJT7HyJOyIPfTJJFelpRHN514T7TjU0RFYPUpaavI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yb2xs/aW5nc3RvbmUuY29t/LmJyL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDI1LzEyL0ZpbG1l/LWRlLVN0cmFuZ2Vy/LVRoaW5ncy1OZXRm/bGl4LXJldmVsYS1k/dXJhY2FvLWRlLXVs/dGltby1lcGlzb2Rp/by1kYS1zZXJpZS04/MDB4NDUwLmpwZw',
    heroUrl: 'https://imgs.search.brave.com/ZwZJT7HyJOyIPfTJJFelpRHN514T7TjU0RFYPUpaavI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9yb2xs/aW5nc3RvbmUuY29t/LmJyL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDI1LzEyL0ZpbG1l/LWRlLVN0cmFuZ2Vy/LVRoaW5ncy1OZXRm/bGl4LXJldmVsYS1k/dXJhY2FvLWRlLXVs/dGltby1lcGlzb2Rp/by1kYS1zZXJpZS04/MDB4NDUwLmpwZw',
    type: 'series',
    description: 'Quando um menino desaparece, uma pequena cidade descobre um mistério envolvendo experimentos secretos, forças sobrenaturais.',
    seasons: 4,
    director: 'Duffer Brothers',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    language: 'Inglês',
    quality: '4K',
    isNew: true,
  },
  {
    id: '5',
    title: 'Oppenheimer',
    year: 2023,
    rating: 4.7,
    genre: ['Biografia', 'Drama'],
    coverUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=675&fit=crop',
    type: 'movie',
    description: 'A história do físico americano J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.',
    duration: '3h',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon'],
    language: 'Inglês',
    quality: '4K',
    isNew: true,
  },
  {
    id: '6',
    title: 'Dark',
    year: 2017,
    rating: 4.8,
    genre: ['Ficção Científica', 'Mistério'],
    coverUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1200&h=675&fit=crop',
    type: 'series',
    description: 'Uma saga familiar com laços que se estendem por oito décadas revelam uma conspiração sombria de viagem no tempo.',
    seasons: 3,
    director: 'Baran bo Odar',
    cast: ['Louis Hofmann', 'Karoline Eichhorn', 'Lisa Vicari'],
    language: 'Alemão',
    quality: 'HD',
  },
  {
    id: '7',
    title: 'Clube da Luta',
    year: 1999,
    rating: 4.8,
    genre: ['Drama', 'Thriller'],
    coverUrl: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=1200&h=675&fit=crop',
    type: 'movie',
    description: 'Um insonista e um vendedor de sabonetes formam um clube de luta subterrâneo que evolui para algo muito mais sombrio.',
    duration: '2h 19min',
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    language: 'Inglês',
    quality: 'HD',
  },
  {
    id: '8',
    title: 'Parasita',
    year: 2019,
    rating: 4.8,
    genre: ['Thriller', 'Drama'],
    coverUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200&h=675&fit=crop',
    type: 'movie',
    description: 'A família Kims ingenia um plano para se infiltrar na rica família Park.',
    duration: '2h 12min',
    director: 'Bong Joon-ho',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    language: 'Coreano',
    quality: '4K',
    isNew: false,
  },
  {
    id: '9',
    title: 'The Last of Us',
    year: 2023,
    rating: 4.9,
    genre: ['Drama', 'Ação'],
    coverUrl: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=1200&h=675&fit=crop',
    type: 'series',
    description: 'Joel é contratado para contrabandear uma garota adolescente para fora de uma zona de quarentena opressiva.',
    seasons: 2,
    director: 'Craig Mazin',
    cast: ['Pedro Pascal', 'Bella Ramsey', 'Anna Torv'],
    language: 'Inglês',
    quality: '4K',
    isNew: true,
  },
  {
    id: '10',
    title: 'Matrix',
    year: 1999,
    rating: 4.7,
    genre: ['Ação', 'Ficção Científica'],
    coverUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=675&fit=crop',
    type: 'movie',
    description: 'Um hacker descobre que a realidade como a conhece é uma simulação criada por máquinas.',
    duration: '2h 16min',
    director: 'Wachowski',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    language: 'Inglês',
    quality: 'HD',
  },
  {
    id: '11',
    title: 'Wednesday',
    year: 2022,
    rating: 4.6,
    genre: ['Comédia', 'Terror'],
    coverUrl: 'https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?w=1200&h=675&fit=crop',
    type: 'series',
    description: 'Wednesday Addams frequenta a Academia Nevermore enquanto tenta dominar sua habilidade psíquica emergente.',
    seasons: 1,
    director: 'Tim Burton',
    cast: ['Jenna Ortega', 'Gwendoline Christie', 'Riki Lindhome'],
    language: 'Inglês',
    quality: '4K',
    isNew: true,
  },
  {
    id: '12',
    title: 'Duna',
    year: 2021,
    rating: 4.6,
    genre: ['Ficção Científica', 'Aventura'],
    coverUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400&h=600&fit=crop',
    heroUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1200&h=675&fit=crop',
    type: 'movie',
    description: 'Paul Atreides lidera tribos nômades em uma batalha para controlar o planeta deserto Arrakis.',
    duration: '2h 35min',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Zendaya'],
    language: 'Inglês',
    quality: '4K',
    isNew: false,
  },
];

export const CATEGORIES = [
  'Todos',
  'Filmes',
  'Séries',
  'Ação',
  'Drama',
  'Terror',
  'Comédia',
  'Ficção Científica',
  'Crime',
];

export const FEATURED_MOVIE = MOCK_MOVIES[0];
